//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOBSUK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public string or_id { get; set; }
        public string c_id { get; set; }
        public System.DateTime or_data { get; set; }
        public decimal or_total { get; set; }
        public string or_payment { get; set; }
        public string or_sent { get; set; }
        public string or_address { get; set; }
        public Nullable<decimal> or_delivery_day { get; set; }
        public string or_status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order_datail Order_datail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
