//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOBSUK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string m_id { get; set; }
        public string or_id { get; set; }
        public System.DateTime m_date { get; set; }
        public decimal m_deposit { get; set; }
        public decimal m_total { get; set; }
        public decimal m_owe { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
